### PR TITLE
Global datasource property is causing postgres driver to fail to load

### PR DESCRIPTION
**Pull request by davydotcom**

### CODE REVIEW

**Comment by stephanebruckert** [comment]
looks like the exceptions disappeared, but the main page still cannot loads

**Comment by davydotcom** [comment]
For some reason with th 8.0.18 webapp runner it takes a while to startup. It did run for me

**Comment by stephanebruckert** [comment]
Not for me :( Does it work for you with my repository, or one of your own? I think I am having the following problem: http://stackoverflow.com/questions/16151527/avoid-heroku-boot-timeout-on-grails-app
Are you using a free traditional Heroku dyno?

Do you think I could make use of this trick: https://github.com/funfork/heroku-buildpack-grails-earlybind/commit/3ced1668a253bde91f10b2c21d5725d2392916e7
with my current configuration?

Would you be able to share an Heroku app that works with me? There _must_ be a difference...

Thanks for your time

**Comment by davydotcom** [comment]
## you are not if you are using the webapp-runner it avoids the boot timeout issue because it binds to the address at the beginning, however it takes quite a while to startup sometimes. You might try backing down on the webapp runner version

David Estes

On June 10, 2015 at 7:40:00 AM, Stéphane Bruckert (notifications@github.com) wrote:

Not for me :( Does it work for you with my repository, or one of your own? I think I am having the following problem: http://stackoverflow.com/questions/16151527/avoid-heroku-boot-timeout-on-grails-app
Are you using a free traditional Heroku dyno?

Do you think I could make use of this trick: funfork/heroku-buildpack-grails-earlybind@3ced166
with my current configuration?

Would you be able to share an Heroku app that works with me? There must be a difference...

Thanks for your time

**Pull request merged**
